### ISSUE TITLE
naming binary/project

### ISSUE THREAD

**Issue by wael444** [aome510/spotify-player#101]
i noticed that the spotify-player binary is named spotify_player; i think this is pretty inconsistent with the project name which has a dash in it. you could rename the project to a better name (suggestion. 'flack' - spot in swedish, 'spelare' - player in swedish, because the founders of spotify were swedish. i think 'spelare' is a cool name'.

i get confused with launching the player due to the dash or the underscore. maybe the binary can be renamed to `splayer` or `spotifyp` or `sp` (like `spt`)?

**Comment by aome510** [comment]
> i noticed that the spotify-player binary is named spotify_player; i think this is pretty inconsistent with the project name which has a dash in it. you could rename the project to a better name (suggestion. 'flack' - spot in swedish, 'spelare' - player in swedish, because the founders of spotify were swedish. i think 'spelare' is a cool name'.

Thanks for the cool suggestion. I'm also aware of the confusion between the project's name and the binary's name. I'm not too sure about the reason for such confusion, maybe because of historical reason =). 

That said, changing name now would be a big breaking change, so I won't do it. I would suggest you do aliasing so you can use whatever name you want to launch the app
