### ISSUE TITLE
Default theme.toml throws error.

### ISSUE THREAD

**Issue by Foxtrod89** [aome510/spotify-player#117]
**Describe the bug**
Default UI looks horrible, wasn't able to navigate through menu so I decided to plug _theme.toml_ to play around with

**To Reproduce**
I catch this behavior by creating default _theme.toml_

**Expected behavior**
_Spotify player_ will run

**Log and backtrace**
```
spotify_player

Error: missing field `selection_background` for key `themes.palette` at line 148 column 1
```

**Screenshots**
Default settings give me this look
[![FastPic.Ru](https://i121.fastpic.org/thumb/2023/0131/c1/e1a9a73ff11b1a76001e5fdd66c498c1.jpeg)](https://fastpic.org/view/121/2023/0131/e1a9a73ff11b1a76001e5fdd66c498c1.png.html)

**Environment**

- OS: **macOS BigSur 11.6**
- Application version:  **spotify-player 0.10.0**
- Application features: if applicable, provide [cargo features](https://doc.rust-lang.org/cargo/reference/features.html) used to build with `spotify-player`
_cargo install spotify_player --features image --locked_
**Additional context**

**Comment by aome510** [comment]
I guess you're referring to `theme.toml` in the `examples` folder. Recently, I made some changes to the `theme` structure, so you can look into [this](https://github.com/aome510/spotify-player/blob/v0.10.0/examples/theme.toml) instead. 

> Default settings give me this look

The default theme shouldn't give such a look. Can you try running the app using different terminal? My initial guess is that it is because colors are not well supported by your terminal.

**Comment by Foxtrod89** [comment]
Problem  solved by switching off ANSI colors but everything turned black/white now

**Comment by aome510** [comment]
Related: https://github.com/aome510/spotify-player/issues/97. I think it will get better with the new upcoming release, in which I switched to use terminal default colors instead of defining custom themes. 

You can try the latest build of `master` branch. In the meantime, I'll close this issue for now. Feel free to reopen if encountering related issues.
