### ISSUE TITLE
Pause glyph is huge

### ISSUE THREAD

**Issue by 0323pin** [aome510/spotify-player#119]
Hi,

Just updated locally to 0.11.0 and will merge it into out repositories soon. Just a thought ...

Play glyph

![2023-02-04-183318_1366x768_scrot](https://user-images.githubusercontent.com/90570748/216781627-6e3d264c-33db-4db6-8a1e-c9af7a2f59f9.png)

Paus glyph

![2023-02-04-183903_1366x768_scrot](https://user-images.githubusercontent.com/90570748/216781691-58cafa24-aa03-4a87-ad92-0d70de9a1a49.png)

The paus glyph looks huge :(

**Comment by aome510** [comment]
Hi pin, yeah you're right =)). The pause icon is, in fact, 2 characters instead of 1 character like the play icon. The previous pause icon cannot be rendered in some terminals, so I need to change it to a different one.

These icons are configurable in `app.toml`, so you can change it to a different one: https://github.com/aome510/spotify-player/blob/master/examples/app.toml#L13

**Comment by 0323pin** [comment]
@aome510 I'll look into it. Building `hackernews-TUI` right now, need to update that one also :)

**Comment by 0323pin** [comment]
@aome510 fixed, thanks.

Copied the `paus_icon` from v0.10.0 into my `app.toml` and everything is looking good now :)

hn ready also, will merge both later tonight.

**Comment by 0323pin** [comment]
Just FYI, both merged now :)
http://mail-index.netbsd.org/pkgsrc-changes/2023/02/04/msg268968.html
http://mail-index.netbsd.org/pkgsrc-changes/2023/02/04/msg268970.html
