### ISSUE TITLE
Select multiple tracks / execute action on multiple tracks

### ISSUE THREAD

**Issue by bartlibert** [aome510/spotify-player#126]
I'd like to be able to select multiple tracks and then execute the same action (if appropriate) on all those tracks.

For example:
Press 'v' to select a track.
Press 'v' to select another track.
Press 'v' again multiple times to select more tracks.

Press 'g a' for ShowActionsOnSelectedItem
Select "AddToQueue" -> all selected tracks are added to the queue

**Comment by aome510** [comment]
I've thought about implementing multi-selection before. One of my use cases is to start playback from the selected tracks so that it can be treated as a mini-playlist. 

That said, I decided not to mainly because it may(?) complicate the current program structure. Regarding your use case, isn't it better to just implement https://github.com/aome510/spotify-player/issues/125 and execute that shortcut on the focused track multiple times?

**Comment by bartlibert** [comment]
No problem, that would cover most cases I guess.
