### ISSUE TITLE
`playback_window_width` should be `playback_window_height`

### ISSUE THREAD

**Issue by apprehensions** [aome510/spotify-player#143]
**Describe the bug**
the configuration option `playback_window_width` looks like it would specify the width, but it actually specifies the height

i think cuz like width is not really controlled here 
and height is like how tall it is and that is what is changed in the tui

**To Reproduce**
uhh no

**Expected behavior**
its called `playback_window_height`

**Log and backtrace**
i feel sad becuase of the name, thats the log

**Screenshots**
![image](https://user-images.githubusercontent.com/47404953/220673782-82da9091-acb3-41c5-941b-d5f6629656b7.png)

**Environment**
no

**Additional context**

im sorry i cant make a pr because i dont know rust and im scared i will actidentally break the program

**Comment by aome510** [comment]
Yeah, I agree it's quite confusing. It's a width as in terms of a rectangle's width (and length). I'll keep this as-is because some UI codes actually rely on this way of understanding.

> im sorry i cant make a pr because i dont know rust and im scared i will actidentally break the program

Nah, it's always good to learn, especially learning Rust ;). Github should already protect from merging a non-approved PR, so no need to worry about that.

I'll close this issue for now. Feel free to re-open if you have any other questions.

**Comment by apprehensions** [comment]
> I'll close this issue for now. Feel free to re-open if you have any other questions.

https://github.com/aome510/spotify-player/blob/master/examples/theme.toml doesnt contain the `default` theme, which does terminal colors

i have no clue what counts as a terminal color, since i wanna have my own theme rn

**Comment by apprehensions** [comment]
i guess using the keys from `StyleColor` work tho lol.
