### ISSUE TITLE
Fake track repeat

### ISSUE THREAD

**Issue by apprehensions** [aome510/spotify-player#247]
**Is your feature request related to a problem? Please describe.**
I want to play a song on loop.

**Describe the solution you'd like**
(when using the local device) to fake repeat the track by re-playing it after it finishes when the loop on single track is enabled.

**Describe alternatives you've considered**

**Additional context**
Currently, Librespot does not support looping a single track once.

**Comment by apprehensions** [comment]
I believe to make this possible, it would require a custom new 'playback' mode that is not available to Spotify API, as 'repeated once track' behavior is going to be inferred from spotify_player AFAIK.

**Comment by Colonial-Dev** [comment]
For what it's worth, `ncspot` (another Rust/`librespot` based Spotify TUI client) seems to have figured out a hack, although what distinguishes it from this project isn't immediately obvious. I'll try and dig deeper if I can find the time.

**Comment by aome510** [comment]
> For what it's worth, `ncspot` (another Rust/`librespot` based Spotify TUI client) seems to have figured out a hack, although what distinguishes it from this project isn't immediately obvious. I'll try and dig deeper if I can find the time.

The main difference is that `ncspot` itself is an Spotify client, which `spotify_player` uses an integrated client from [librespot](https://github.com/librespot-org/librespot). In other words, it's easier for `ncspot` to implement the hack as they own the client implementation.

**Comment by apprehensions** [comment]
Is it that difficult to just check if the user has 'repeat once' and just replay the song after it ends? Or am I underestimating how difficult it is?

**Comment by aome510** [comment]
`spotify_player` operates on API boundary and streaming client is just an "add-on" compared to `ncspot` with streaming client as the main component. As a result, the app cannot have any assumption regarding the streaming client's behaviour.

> Is it that difficult to just check if the user has 'repeat once' and just replay the song after it ends?

The problem is that you don't know when user has 'repeat once'. The integrated streaming client will automatically switch to `repeat context` mode as `repeat once` is not supported. As a result, when you query `get-repeat-mode` API, the returned mode will be `repeat context`.

There are different ways to implement the "hack". The easiest one is to start a new "one-track" playback if user wants to change the repeat mode to `repeat once`. The drawback of this approach is that you will lose the previous context, or you cannot playback the previous context when switching to different repeat mode.

Another approach is to add a separate `fake track repeat` mode and a command to enable/disable the mode. The integrated client can be updated to queue the current song when it is about to end. I would prefer this approach as a workaround for the integrated client's [limitation](https://github.com/librespot-org/librespot/issues/19). Can start working on this when I'm free.

**Comment by apprehensions** [comment]
YAYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY

**Comment by aome510** [comment]
Implemented with #410. @apprehensions can you try the latest `master`? The command is `ToggleFakeTrackRepeatMode` with default binding `M-R` (alt + R). Should see `repeat: track (fake)` if the fake track repeat mode is enabled.

**Comment by apprehensions** [comment]
It plays the 'fake repeat' track twice, and then plays the next song in queue, then the 'fake repeat' track again.

**Comment by aome510** [comment]
The timing between events seems too short. Did you seek to the end of the track to test the feature? The `queue the current song when it is about to end` logic only applies once every 10s to avoid making duplicated requests. That might be the reason why it doesn't work well

**Comment by apprehensions** [comment]
No.. The song I was listening to was 9 seconds. I am unable to test right now but given this I suppose it males sense.

**Comment by aome510** [comment]
ahh, suport short song won't work with fake repeat mode unfortunately xD.
