### ISSUE TITLE
FR: `spotify_player playback start`

### ISSUE THREAD

**Issue by chrisgrieser** [aome510/spotify-player#336]
**Is your feature request related to a problem? Please describe.**
`spotify_player playback play` does *continue* playback if you have a paused playback. However, it does not *start* playback if you currently have no playback.

**Describe the solution you'd like**
Add a command `spotify_player playback start`. Alternatively, have `spotify_player playback play` automatically start playback if there is no paused playback.

**Describe alternatives you've considered**
Starting playback via the web-interface, then immediately running `spotify_player playback pause` results in a state where you can use `play`.

**Additional context**
Using the interactive client (just `spotify_player`, then `space`) works to start a playback.

**Comment by aome510** [comment]
I have trouble understanding this feature request. If there is no playback, what kind of playback should the player starts? Note that `spotify_player` does provide `playback start context/liked/radio` subcommands that starts a specific playback.

**Comment by chrisgrieser** [comment]
> If there is no playback, what kind of playback should the player starts?
The last playback that was active

Assuming I am starting the day, and just want to continue whatever playback I had the day before:
- When I do `spotify_player` and press `space`, it correctly resumes the last playback from the day before. 
- If I say "Alexa, continue" to my Alexa device, it resumes the last playback from the day before. 
- `spotify_player playback play`, however, does not behave that way, it errors with `Bad request: no playback found`

**Comment by aome510** [comment]
Thanks for the additional context. Normally, if the listening device becomes inactive for a while, you need to manually `connect` to it before controlling the playback. 

The reason why it works for `spotify_player` is that the app **automatically** connects to **an integrated device** if there is no active device on startup. _"Alexa, continue"_ works probably because Alexa itself is a device so it can just connect to itself before controlling the playback. It's difficult from `spotify_player` CLI's perspective as the CLI cannot know which device you want to start the playback.

`spotify_player` provides `connect` command and you will need manually specify a device's id or name to connect to.

`no playback found` is not a good error message. Instead, it should include a suggestion telling user to run `connect` command if there is no active playback.

**Comment by chrisgrieser** [comment]
Oh see, thank you. That clears it up.
