### ISSUE TITLE
Failure to authenticate after fresh Arch install

### ISSUE THREAD

**Issue by vannotz** [aome510/spotify-player#547]
Did a fresh install of Arch (switch from Artix) and I can't seem to login to my spotify account with spotify-player (nor with ncspot), it gives "Failed to authenticate, 2 tries left", and I know for a fact that the credentials are right since I can login from my browser. One thing to note is that, when logging in from the Browser, spotify asks to verify the login with a set of numbers sent to my email, maybe since that these spotify terminal players don't support that feature it simply fails.
I am using the base AUR package with no extra features built in.

Seems to be related to this Family Plan problem as reported in ncspot's github, https://github.com/hrkfdn/ncspot/issues/1500

**Comment by ManiArasteh** [comment]
Nope. It's not related to that. See #520.

**Comment by ManiArasteh** [comment]
Use [librespot-auth repository](https://github.com/dspearson/librespot-auth) to create credentials.json file (make sure you installed official Spotify client. I didn't test with web player and mobile app, but test it if you like) and copy it to ~/.cache/spotify-player

**Comment by vannotz** [comment]
> Use [librespot-auth repository](https://github.com/dspearson/librespot-auth) to create credentials.json file (make sure you installed official Spotify client. I didn't test with web player and mobile app, but test it if you like) and copy it to ~/.cache/spotify-player

How would this work? I'm not sure what commands to run with librespot-auth

**Comment by ManiArasteh** [comment]
> How would this work? I'm not sure what commands to run with librespot-auth

First clone [librespot-auth](https://github.com/dspearson/librespot-auth) with `git clone https://github.com/dspearson/librespot-auth.git`

Build it using `cargo build` 

If you don't have Cargo, install it using Rustup. Install Rustup using `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`. 

Run it (Maybe you encounter error `Access denied`. grant permission with `chmod`) (Executable file is in librespot-auth/target/debug/ named librespot-auth (I don't know because I'm on Windows. maybe it has another file extension. If you're not sure run `file <executable-filename>`. )).

Then go to Spotify official client and select "Speaker" in Spotify Connect section (The popup you switch to your another device). It will save `credentials.json` in application's executable. Copy it to ~/.cache/spotify-player. You can pass --path argument to ~/.cache/spotify-player to save file directly in app's cache directory (e.g. run `librespot-auth --path ~/.cache/spotify-player`).

Finished. Now run Spotify player. (Sorry. It was too long)

**Comment by vannotz** [comment]
Worked flawlessly for me, thank you, I think I'll close this issue so that the main discussion is focused in the other issue.
