### ISSUE TITLE
Queue track

### ISSUE THREAD

**Issue by bartlibert** [aome510/spotify-player#72]
One thing I really miss is the possibility to add a track or album to the queue.
Rspotify has support for this: [documentation](https://docs.rs/rspotify/0.11.5/rspotify/clients/oauth/trait.OAuthClient.html#method.add_item_to_queue), so I guess it should be possible?

It would be nice to just be able to press a key (spotify-tui uses 'z' for example, but anything else would be fine) and add the currently selected item to the queue. To be honest, to me this only makes sense for tracks or albums, but maybe you have some other ideas?

**Comment by aome510** [comment]
> One thing I really miss is the possibility to add a track or album to the queue.
Rspotify has support for this: [documentation](https://docs.rs/rspotify/0.11.5/rspotify/clients/oauth/trait.OAuthClient.html#method.add_item_to_queue), so I guess it should be possible?

Yeah, given the already supported API, adding a "add-to-queue" command should be easy.

I remembered that back then, I didn't implement queue-related features because spotify doesn't provide an API to get items in queue.

**Comment by aome510** [comment]
@bartlibert sorry for the delay. I have implemented "add-track-to-queue" support in #73. You can initiate the action by calling either `ShowActionsOnSelectedItem` (on track) or `ShowActionsOnCurrentTrack` then finding `AddToQueue` action.

Currently, it only supports track as official API only supports track/episode, but can be extended to album, artist, etc. Before supporting those, I'm looking into a good way to implement/integrate a `Queue` page to show queued tracks.

As for now, I'll close this issue. Feel free to re-open if you encounter any issues or have any questions.

**Comment by bartlibert** [comment]
@aome510 No need to apologize, the work you're doing here is high quality and always quick, thanks a lot!
