### ISSUE TITLE
Playerctl Volume Control + Possible Podcast Support?

### ISSUE THREAD

**Issue by Selmer443** [aome510/spotify-player#77]
Hi, I've been using spotify-player for quite a while now, I think everything is great but podcast support would make the app even more complete in my opinion. The other thing I had a question about was volume control through playerctl, or any other way to control volume through the command line, I'm aware of an easy way to manage volume using https://gitlab.com/axdsop/nix-dotfiles/-/blob/master/Configs/polybar/scripts/mpris_player/mpris_player_control and the command "mpris_player_control -p spotify_player -V 100". However the volume adjustments aren't reflected in the spotify-player interface. My current workaround is just using xdotool but it's not perfect: 

WINDOW=$(xdotool search --name spotify_player)

xdotool key --window "$WINDOW" minus

Thanks for your continued support of this project :)

**Comment by aome510** [comment]
Hi @Selmer443, thanks for using the app :). 

I haven't really used Podcast Spotify. That's why it wasn't supported in the first place. That said, adding one shouldn't be too difficult.

Regarding the volume control, `spotify_player` uses a third party library [`souvlaki`](https://docs.rs/souvlaki/latest/souvlaki/enum.MediaControlEvent.html) for external media control (play, pause, next, etc). As you can see from the link, the library doesn't support volume events, so supporting those is not possible. I would suggest raising an issue the library repo (https://github.com/Sinono3/souvlaki).

**Comment by Selmer443** [comment]
thanks, I will make sure to create an issue there, thanks again for the quick responses!
